import{wouldCreateDependencyCycle,type Dependency}from'../work/v2Planning';
export interface AutopilotMilestone{clientId:string;name:string;startDate?:string;dueDate?:string;estimatedMinutes?:number}
export interface AutopilotTask{clientId:string;milestoneClientId:string;title:string;assigneeMembershipIds:string[];estimatedMinutes:number;startDate?:string;dueDate?:string}
export interface AutopilotDraft{brief:string;project:{name:string;description?:string;startDate?:string;dueDate?:string};milestones:AutopilotMilestone[];tasks:AutopilotTask[];dependencies:Dependency[];requiredSkills:string[];risks:string[];deliverables:string[]}
export interface AutopilotApprovalContext{organizationId:string;actorMembershipId:string;role:'employee'|'org_admin'|'platform_admin';activeMembershipIds:Set<string>;confirmed:boolean}
export interface TrustedAutopilotGateway{createApprovedPlan(context:AutopilotApprovalContext,draft:AutopilotDraft):Promise<{projectId:string;auditId:string}>}
export function validateAutopilotDraft(draft:AutopilotDraft,context:AutopilotApprovalContext):string[]{const errors:string[]=[];if(!draft.brief.trim()||!draft.project.name.trim())errors.push('brief_and_project_required');const milestones=new Set(draft.milestones.map(m=>m.clientId));const tasks=new Set(draft.tasks.map(t=>t.clientId));if(milestones.size!==draft.milestones.length||tasks.size!==draft.tasks.length)errors.push('duplicate_client_id');for(const m of draft.milestones)if(m.startDate&&m.dueDate&&m.dueDate<m.startDate)errors.push(`invalid_dates:${m.clientId}`);for(const t of draft.tasks){if(!milestones.has(t.milestoneClientId))errors.push(`unknown_milestone:${t.clientId}`);if(t.estimatedMinutes<0)errors.push(`invalid_effort:${t.clientId}`);if(t.startDate&&t.dueDate&&t.dueDate<t.startDate)errors.push(`invalid_dates:${t.clientId}`);for(const member of t.assigneeMembershipIds)if(!context.activeMembershipIds.has(member))errors.push(`invalid_member:${member}`);}const accepted:Dependency[]=[];for(const d of draft.dependencies){if(!tasks.has(d.predecessorId)||!tasks.has(d.successorId))errors.push('unknown_dependency_task');else if(wouldCreateDependencyCycle(accepted,d))errors.push('dependency_cycle');else accepted.push(d);}return[...new Set(errors)];}
export async function approveAutopilotDraft(draft:AutopilotDraft,context:AutopilotApprovalContext,gateway:TrustedAutopilotGateway){if(context.role!=='org_admin')throw new Error('org_admin_required');if(!context.confirmed)throw new Error('confirmation_required');const errors=validateAutopilotDraft(draft,context);if(errors.length)throw new Error(`invalid_draft:${errors.join(',')}`);return gateway.createApprovedPlan(context,draft);}
export type AgentAuthority='read'|'draft'|'execute';
export function authorizeAgentRun(config:{enabled:boolean;authority:AgentAuthority},requested:AgentAuthority,confirmed=false){if(!config.enabled)throw new Error('agent_disabled');const rank={read:0,draft:1,execute:2};if(rank[requested]>rank[config.authority])throw new Error('authority_exceeded');if(requested==='execute'&&!confirmed)throw new Error('confirmation_required');return true;}
