import {describe,expect,it,vi} from 'vitest';
import {adminCommandCenter,employeeCommandCenter} from './commandCenter';
import {replayOfflineQueue,type OfflineOperation,type OfflineStore} from './offlineQueue';
const scope={tenantId:'t',organizationId:'o',membershipId:'m'};
class MemoryStore implements OfflineStore{constructor(public records:OfflineOperation[]){}async list(){return this.records;}async put(v:OfflineOperation){this.records=this.records.filter(x=>x.id!==v.id).concat(v);}async remove(id:string){this.records=this.records.filter(x=>x.id!==id);}}
describe('offline authority and command projections',()=>{
 it('rejects queued work before replay when membership is revoked',async()=>{const op:OfflineOperation={id:'1',idempotencyKey:'key',scope,entityType:'task',operation:'update',payload:{progress:10},createdAt:'now',state:'queued'};const store=new MemoryStore([op]);const replay=vi.fn();const result=await replayOfflineQueue(store,{revalidate:async()=>false,replay});expect(result[0]).toMatchObject({state:'rejected',failureCode:'authorization_revoked'});expect(replay).not.toHaveBeenCalled();});
 it('preserves server conflict state for user reconciliation',async()=>{const op:OfflineOperation={id:'1',idempotencyKey:'key',scope,entityType:'task',operation:'update',payload:{progress:10},baseRevision:2,createdAt:'now',state:'queued'};const store=new MemoryStore([op]);const [result]=await replayOfflineQueue(store,{revalidate:async()=>true,replay:async()=>({status:'conflict',failureCode:'revision_changed'})});expect(result).toMatchObject({state:'conflict',failureCode:'revision_changed'});});
 it('builds role-specific projections without employee scoring',()=>{const items=[{id:'a',title:'Blocked',status:'blocked' as const,progress:20,dueDate:'2026-01-01',estimatedMinutes:100,assigneeMembershipIds:['m']}];const employee=employeeCommandCenter(items,[],[],[],[],new Date('2026-02-01'));expect(employee).toMatchObject({blocked:[items[0]],overdue:[items[0]],activeSession:null});const admin=adminCommandCenter(items,[],[{membershipId:'m',availableMinutes:60}],[],[]);expect(admin).toMatchObject({projectProgress:20,blockedCount:1});expect(admin.workload[0].overloaded).toBe(true);});
});
