import { supabase } from '../../lib/supabase';
import { createOperationalError } from '../../observability/operationalError';
import { reportOperationalError } from '../../observability/telemetry';
import type { OrganizationScope } from './types';
import type { AgentConfig,AiState,AutomationRule,Conversation,Evidence,FileMetadata,Message,Pass3Repository,SearchResult,UploadPreparation,UploadRequest } from './pass3Types';
type Row=Record<string,unknown>;
function fail(op:string,error:unknown):never{const event=createOperationalError(op,'service',error,{code:'unknown',message:'The authorized operation could not be completed.',retryable:true});void reportOperationalError(event);throw event;}
function one(op:string,data:unknown,error:unknown):Row{if(error)fail(op,error);if(!data)fail(op,new Error('No durable result'));return data as Row;}
const conversation=(r:Row):Conversation=>({id:String(r.id),organizationId:String(r.organization_id),kind:String(r.kind),title:r.title as string|null,projectId:r.project_id as string|null,milestoneId:r.milestone_id as string|null,taskId:r.task_id as string|null,updatedAt:String(r.updated_at)});
const message=(r:Row):Message=>({id:String(r.id),organizationId:String(r.organization_id),conversationId:String(r.conversation_id),authorMembershipId:r.author_membership_id as string|null,body:String(r.body),kind:r.kind as 'user'|'system',createdAt:String(r.created_at),pinnedAt:r.pinned_at as string|null});
const file=(r:Row):FileMetadata=>({id:String(r.id),organizationId:String(r.organization_id),fileName:String(r.file_name),mimeType:String(r.mime_type),sizeBytes:Number(r.size_bytes),projectId:r.project_id as string|null,taskId:r.task_id as string|null,messageId:r.message_id as string|null,createdAt:String(r.created_at)});
const evidence=(r:Row):Evidence=>({id:String(r.id),organizationId:String(r.organization_id),taskId:String(r.task_id),subtaskId:r.subtask_id as string|null,kind:String(r.kind),status:String(r.status),summary:r.summary as string|null,uri:r.uri as string|null,createdAt:String(r.created_at)});
const automation=(r:Row):AutomationRule=>({id:String(r.id),organizationId:String(r.organization_id),name:String(r.name),status:r.status as AutomationRule['status'],trigger:r.trigger_spec as Record<string,unknown>,condition:r.condition_spec as Record<string,unknown>,action:r.action_spec as Record<string,unknown>,requiresApproval:Boolean(r.requires_approval),revision:Number(r.revision)});
const agent=(r:Row):AgentConfig=>({id:String(r.id),organizationId:String(r.organization_id),agentType:String(r.agent_type),enabled:Boolean(r.enabled),authority:r.authority as AgentConfig['authority'],projectId:r.project_id as string|null,revision:Number(r.revision),lastRunAt:r.last_run_at as string|null,lastStatus:r.last_status as string|null,lastSummary:r.last_summary as string|null});
async function rows(table:string,scope:OrganizationScope,op:string):Promise<Row[]>{const {data,error}=await supabase.from(table).select('*').eq('organization_id',scope.organizationId).eq('tenant_id',scope.tenantId);if(error)fail(op,error);return (data??[]) as unknown as Row[];}

export const supabasePass3Repository:Pass3Repository={
 async listConversations(s){return (await rows('conversations',s,'communication.list')).map(conversation);},
 async listMessages(s,id,cursor,limit=50){let q=supabase.from('messages').select('*').eq('organization_id',s.organizationId).eq('conversation_id',id).order('created_at',{ascending:false}).limit(Math.min(Math.max(limit,1),100));if(cursor)q=q.lt('created_at',cursor);const {data,error}=await q;if(error)fail('messages.list',error);const items=((data??[]) as unknown as Row[]).map(message);return{items,nextCursor:items.length===limit?items.at(-1)?.createdAt??null:null};},
 async createConversation(s,i){const {data,error}=await supabase.rpc('create_conversation',{p_organization_id:s.organizationId,p_kind:i.kind,p_title:i.title,p_participants:i.participants,p_department_id:i.departmentId??null,p_project_id:i.projectId??null,p_milestone_id:i.milestoneId??null,p_task_id:i.taskId??null});return conversation(one('communication.create',data,error));},
 async postMessage(_s,id,body,mentions=[]){const {data,error}=await supabase.rpc('post_message',{p_conversation_id:id,p_body:body,p_mentions:mentions});return message(one('messages.create',data,error));},
 async setReaction(id,emoji,active){const {error}=await supabase.rpc('set_message_reaction',{p_message_id:id,p_emoji:emoji,p_active:active});if(error)fail('messages.reaction',error);},
 async setMessagePin(id,pinned){const{data,error}=await supabase.rpc('set_message_pin',{p_message_id:id,p_pinned:pinned});return message(one('messages.pin',data,error));},
 async listFiles(s,c){let q=supabase.from('files').select('*').eq('organization_id',s.organizationId).eq('tenant_id',s.tenantId).is('deleted_at',null);if(c.projectId)q=q.eq('project_id',c.projectId);if(c.taskId)q=q.eq('task_id',c.taskId);if(c.messageId)q=q.eq('message_id',c.messageId);const {data,error}=await q;if(error)fail('files.list',error);return((data??[]) as unknown as Row[]).map(file);},
 async archiveFile(f){const {error}=await supabase.from('files').update({deleted_at:new Date().toISOString()}).eq('id',f.id).eq('organization_id',f.organizationId).is('deleted_at',null);if(error)fail('files.archive',error);},
 async prepareUpload(_s,_r:UploadRequest):Promise<UploadPreparation>{return{status:'configuration_required',message:'Private object storage signing is not configured. No upload was created.'};},
 async listEvidence(s,taskId){const {data,error}=await supabase.from('evidence_records').select('*').eq('organization_id',s.organizationId).eq('task_id',taskId);if(error)fail('evidence.list',error);return((data??[]) as unknown as Row[]).map(evidence);},
 async submitLinkEvidence(s,i){const {data,error}=await supabase.from('evidence_records').insert({tenant_id:s.tenantId,organization_id:s.organizationId,task_id:i.taskId,subtask_id:i.subtaskId??null,kind:i.kind,uri:i.uri,summary:i.summary??null,submitted_by:s.membershipId}).select().single();return evidence(one('evidence.submit',data,error));},
 async listAutomationRules(s){return(await rows('automation_rules',s,'automation.list')).map(automation);},
 async saveAutomationRule(s,actor,i){const values={tenant_id:s.tenantId,organization_id:s.organizationId,name:i.name.trim(),status:i.status??'draft',trigger_spec:i.trigger??{},condition_spec:i.condition??{},action_spec:i.action??{},requires_approval:i.requiresApproval??true,created_by:actor};const request=i.id?supabase.from('automation_rules').update({...values,revision:(i.revision??0)+1}).eq('id',i.id).eq('organization_id',s.organizationId).eq('revision',i.revision??0):supabase.from('automation_rules').insert(values);const {data,error}=await request.select().maybeSingle();return automation(one('automation.save',data,error));},
 async executeAutomation(r){const {data,error}=await supabase.rpc('run_notification_automation',{p_rule_id:r.id,p_expected_revision:r.revision});return String(one('automation.execute',data,error).id);},
 async search(s,q,limit=20){const {data,error}=await supabase.rpc('search_work_os',{p_organization_id:s.organizationId,p_query:q.trim(),p_limit:limit});if(error)fail('search.query',error);return((data??[]) as unknown as Row[]).map((r):SearchResult=>({entityType:String(r.entity_type),entityId:String(r.entity_id),title:String(r.title),subtitle:String(r.subtitle),href:String(r.href)}));},
 async listAgentConfigs(s){return(await rows('agent_configs',s,'agents.list')).map(agent);},
 async saveAgentConfig(s,actor,i){const values={tenant_id:s.tenantId,organization_id:s.organizationId,agent_type:i.agentType,enabled:i.enabled??false,authority:i.authority??'read',project_id:i.projectId??null,configured_by:actor};const request=i.id?supabase.from('agent_configs').update({...values,revision:(i.revision??0)+1}).eq('id',i.id).eq('revision',i.revision??0):supabase.from('agent_configs').insert(values);const {data,error}=await request.select().maybeSingle();return agent(one('agents.save',data,error));},
 async getAiState(_s):Promise<AiState>{const {data,error}=await supabase.functions.invoke('ai-runtime',{body:{operation:'configuration_status'}});if(error||data?.status!=='ready')return{status:'configuration_required',message:'AI provider configuration is required. No response was generated.'};return{status:'ready',message:'AI provider is configured.'};},
};
