import { useState,type FormEvent,type ReactNode } from 'react';
import { AlertCircle,ArrowRight,CheckCircle2,ChevronRight,Circle,Clock,Flag,Layers3,PauseCircle,Plus,RefreshCw,StopCircle,X } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { useWork } from '../work/useWork';
import type { WorkSession,Subtask } from './types';
import { useV2Module,type V2Module } from './useV2Module';
import type { WorkTask,WorkTaskStatus } from '../work/types';
import './my-work-v7a.css';

const title=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const display=(record:Record<string,unknown>)=>String(record.name??record.title??record.displayName??record.kind??record.id);

export function V2ModuleScreen({module}:{module:V2Module}){
  const state=useV2Module(module);const work=useWork();const [form,setForm]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!state.scope||!state.user)return;setSaving(true);setMessage('');const data=new FormData(e.currentTarget);try{await state.execute<unknown>(r=>{switch(module){case'milestones':return r.createMilestone(state.scope!,state.user!.id,{projectId:String(data.get('projectId')),name:String(data.get('name')),dueDate:String(data.get('dueDate')||''),estimatedMinutes:Number(data.get('effort'))||undefined});case'subtasks':return r.createSubtask(state.scope!,state.user!.id,{taskId:String(data.get('taskId')),title:String(data.get('name')),estimatedMinutes:Number(data.get('effort'))||undefined});case'departments':return r.createDepartment(state.scope!,String(data.get('name')));case'skills':return r.createSkill(state.scope!,{name:String(data.get('name')),description:String(data.get('description')||'')});default:throw new Error('Creation is not available from this view.');}});setForm(false);}catch{setMessage('The record was not saved. Reload and check your permission or the latest revision.');}finally{setSaving(false);}};
  if(state.loading)return <Status heading={`Loading ${title(module)}…`}>Authoritative organization data is loading.</Status>;
  if(state.error)return <Status heading={`${title(module)} unavailable`}><span>{state.error.message}</span><Button onClick={()=>void state.reload()}><RefreshCw/>Retry</Button></Status>;
  const canCreate=state.isAdmin&&['milestones','subtasks','departments','skills'].includes(module);
  return <main className="premium-page"><header className="flex flex-wrap items-end justify-between gap-3 border-b pb-5"><div><p className="premium-eyebrow">Work OS · {module}</p><h1 className="premium-title mt-1">{title(module)}</h1><p className="mt-1 text-sm text-muted-foreground">Validated, organization-scoped records. Browser state is not authorization.</p></div>{canCreate&&<Button className="rounded-xl" onClick={()=>setForm(v=>!v)}><Plus/>New {title(module).replace(/s$/,'')}</Button>}</header>
    {form&&<form aria-label={`Create ${module}`} onSubmit={submit} className="premium-surface grid max-w-xl gap-3 p-5"><Input name="name" required placeholder={module==='subtasks'?'Subtask title':`${title(module)} name`}/>{module==='skills'&&<Input name="description" placeholder="Description"/>}{module==='milestones'&&<><select name="projectId" required className="h-10 rounded-lg border bg-background px-3"><option value="">Project</option>{work.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Input name="dueDate" type="date"/></>}{module==='subtasks'&&<select name="taskId" required className="h-10 rounded-lg border bg-background px-3"><option value="">Task</option>{work.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select>}{['milestones','subtasks'].includes(module)&&<Input name="effort" type="number" min="0" placeholder="Estimated minutes"/>}<Button disabled={saving}>{saving?'Saving…':'Save'}</Button>{message&&<p role="alert" className="text-sm text-destructive">{message}</p>}</form>}
    {!state.records.length?<Status heading={`No ${title(module).toLowerCase()} yet`}>Nothing authorized is available in this organization.</Status>:<div className="premium-surface divide-y overflow-hidden">{state.records.map(raw=>{const record=raw as Record<string,unknown>;return <article key={String(record.id)} className="flex flex-wrap items-center justify-between gap-3 p-4 transition-colors hover:bg-muted/35"><div><h2 className="font-medium">{display(record)}</h2><p className="text-xs text-muted-foreground">{String(record.status??record.role??record.startedAt??'Active')}</p></div><p className="premium-status">{record.progress!==undefined?`${record.progress}%`:record.availableMinutes!==undefined?`${record.availableMinutes} min available`:'Active'}</p>{module==='sessions'&&!record.endedAt&&record.membershipId===state.scope?.membershipId&&<Button variant="outline" onClick={()=>void state.execute(r=>r.stopWorkSession(record as unknown as WorkSession))}><StopCircle/>Stop</Button>}</article>;})}</div>}
  </main>;
}

export function WorkSessionScreen(){const state=useV2Module('sessions');const active=(state.records as WorkSession[]).find(s=>!s.endedAt&&s.membershipId===state.scope?.membershipId);return <main className="p-6 space-y-5"><h1 className="text-2xl font-semibold">Work Session</h1><p className="text-muted-foreground">Capture time without screenshots, activity monitoring, or employee scoring.</p>{state.loading?<p>Loading active session…</p>:active?<div className="rounded-xl border bg-card p-5"><Clock/><h2 className="font-medium mt-2">Started {new Date(active.startedAt).toLocaleString()}</h2><Button className="mt-4" onClick={()=>void state.execute(r=>r.stopWorkSession(active))}><StopCircle/>Stop session</Button></div>:<Button onClick={()=>void state.execute(r=>r.startWorkSession(state.scope!,{}))}><Clock/>Start session</Button>}</main>}

type WorkLens='focus'|'now'|'next'|'blocked'|'completed'|'archived';
const lenses:Array<{id:WorkLens;label:string}>= [{id:'focus',label:'Focus'},{id:'now',label:'Now'},{id:'next',label:'Next'},{id:'blocked',label:'Blocked'},{id:'completed',label:'Completed'},{id:'archived',label:'Archived'}];
const taskSignal=(status:WorkTaskStatus)=>status==='blocked'?'danger':status==='completed'?'done':status==='in_progress'?'live':'queued';
const tasksForLens=(tasks:WorkTask[],lens:WorkLens)=>{const open=tasks.filter(t=>!['completed','archived'].includes(t.status));if(lens==='focus')return open.slice(0,6);if(lens==='now')return tasks.filter(t=>t.status==='in_progress');if(lens==='next')return tasks.filter(t=>t.status==='todo');if(lens==='blocked')return tasks.filter(t=>t.status==='blocked');if(lens==='archived')return tasks.filter(t=>t.status==='archived');return tasks.filter(t=>t.status==='completed');};
const isSubtaskComplete=(subtask:Subtask)=>subtask.status==='completed'||subtask.progress>=100;

export function MyWorkScreen(){
  const work=useWork();const subtasksState=useV2Module('subtasks');const [lens,setLens]=useState<WorkLens>('focus');const [selectedId,setSelectedId]=useState<string|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
  if(work.loading)return <Status heading="Loading My Work…">Loading authorized assignments.</Status>;if(work.error)return <Status heading="My Work unavailable"><span>{work.error.message}</span><Button onClick={()=>void work.reload()}><RefreshCw/>Retry</Button></Status>;
  const subtasks=subtasksState.records as Subtask[];const visible=tasksForLens(work.tasks,lens);const selected=work.tasks.find(t=>t.id===selectedId)??null;const now=work.tasks.filter(t=>t.status==='in_progress').length;const blocked=work.tasks.filter(t=>t.status==='blocked').length;const finished=work.tasks.filter(t=>t.status==='completed').length;
  const chunksFor=(taskId:string)=>subtasks.filter(item=>item.taskId===taskId);const selectedChunks=selected?chunksFor(selected.id):[];const selectedDone=selectedChunks.filter(isSubtaskComplete).length;
  const update=async(task:WorkTask,patch:{status?:WorkTaskStatus;progress?:number})=>{setSaving(true);setMessage('');try{await work.updateTask(task,patch);setMessage('Saved to the authoritative work record.');}catch{setMessage('Change not saved. Reload and check your permission or latest revision.');}finally{setSaving(false);}};
  return <main className="mw7-page">
    <header className="mw7-header"><div><p className="mw7-kicker">DAILY EXECUTION · MY WORK</p><h1>Make today count.</h1><p>Your focused queue across every authorized project—without leaving this workspace.</p></div><div className="mw7-pulse"><span><b>{now}</b> in motion</span><span className={blocked?'is-risk':''}><b>{blocked}</b> blocked</span><span><b>{finished}</b> delivered</span></div></header>
    <nav className="mw7-lenses" aria-label="My Work views">{lenses.map(item=>{const count=tasksForLens(work.tasks,item.id).length;return <button key={item.id} className={lens===item.id?'is-active':''} onClick={()=>{setLens(item.id);setSelectedId(null);}}><span>{item.label}</span><small>{count}</small></button>})}</nav>
    <div className={`mw7-cockpit ${selected?'has-inspector':''}`}>
      <section className="mw7-queue"><header><div><span className="mw7-lens-mark"><Layers3/></span><div><p>{lens==='focus'?'FOCUS QUEUE':`${lens.toUpperCase()} WORK`}</p><h2>{lens==='focus'?'Open work':title(lens)}</h2></div></div><small>{visible.length} {visible.length===1?'outcome':'outcomes'} · ordered for focus</small></header>
        {visible.length?<div className="mw7-list">{visible.map((task,index)=>{const chunks=chunksFor(task.id);const completedChunks=chunks.filter(isSubtaskComplete).length;return <button className={`mw7-task ${selectedId===task.id?'is-selected':''}`} key={task.id} onClick={()=>setSelectedId(task.id)}><span className="mw7-order">{String(index+1).padStart(2,'0')}</span><span className={`mw7-state is-${taskSignal(task.status)}`}><i/></span><span className="mw7-task-copy"><small>{task.projectName}</small><strong>{task.title}</strong><span>{task.description||'No task brief has been added yet.'}</span></span><span className="mw7-chunk-summary">{subtasksState.loading?'Loading chunks…':chunks.length?`${completedChunks}/${chunks.length} chunks`:'No chunks'}</span><span className={`mw7-status is-${taskSignal(task.status)}`}>{title(task.status)}</span><ChevronRight className="mw7-arrow"/></button>})}</div>:<div className="mw7-empty"><CheckCircle2/><h3>Nothing in {lens}</h3><p>Your authorized working set is clear in this view.</p></div>}
      </section>
      <aside className="mw7-inspector" aria-label="Task inspector" aria-hidden={!selected}>{selected&&<><header><div><p>TASK INSPECTOR</p><span className={`mw7-status is-${taskSignal(selected.status)}`}>{title(selected.status)}</span></div><button onClick={()=>setSelectedId(null)} aria-label="Close task inspector"><X/></button></header><div className="mw7-inspector-scroll"><section className="mw7-task-title"><small>{selected.projectName}</small><h2>{selected.title}</h2><p>{selected.description||'No task brief has been added yet.'}</p></section><section className="mw7-context"><p>DELIVERY CONTEXT</p><div><span><Layers3/>Project</span><strong>{selected.projectName}</strong></div><div><span><Flag/>Milestone</span><strong>Not linked in current work record</strong></div></section><section className="mw7-checkpoints"><div><p>WORK CHUNKS</p><span>{subtasksState.loading?'Loading…':`${selectedDone} / ${selectedChunks.length} complete`}</span></div>{subtasksState.error?<p className="mw7-chunk-empty">Work chunks could not be loaded from the authorized record.</p>:selectedChunks.length?selectedChunks.map((chunk,index)=><div className="mw7-real-chunk" key={chunk.id}><span>{isSubtaskComplete(chunk)?<CheckCircle2/>:chunk.status==='blocked'?<PauseCircle/>:chunk.status==='in_progress'?<ArrowRight/>:<Circle/>}</span><div><small>CHUNK {index+1}</small><strong>{chunk.title}</strong></div><em>{title(chunk.status)}</em></div>):<p className="mw7-chunk-empty">No real work chunks are linked to this task yet. Work OS will not invent checkpoint data.</p>}</section><section className="mw7-actions"><p>LIFECYCLE</p>{selected.status==='todo'&&<button disabled={saving} onClick={()=>void update(selected,{status:'in_progress'})}><ArrowRight/>Start now</button>}{selected.status==='in_progress'&&<button disabled={saving} onClick={()=>void update(selected,{status:'blocked'})}><PauseCircle/>Mark blocked</button>}{selected.status==='blocked'&&<button disabled={saving} onClick={()=>void update(selected,{status:'in_progress'})}><ArrowRight/>Resume work</button>}{selected.status!=='completed'&&selected.status!=='archived'&&<button disabled={saving} onClick={()=>void update(selected,{status:'completed',progress:100})}><CheckCircle2/>Complete task</button>}</section>{message&&<p className="mw7-save-message" role="status">{message}</p>}</div></>}</aside>
    </div>
  </main>}
export const MilestonesScreen=()=> <V2ModuleScreen module="milestones"/>;export const AssignmentsScreen=()=> <V2ModuleScreen module="assignments"/>;export const WorkReportsScreen=()=> <V2ModuleScreen module="dependencies"/>;
export const PeopleScreen=()=> <V2ModuleScreen module="people"/>;export const DepartmentsScreen=()=> <V2ModuleScreen module="departments"/>;export const TimeEntriesScreen=()=> <V2ModuleScreen module="time"/>;export const SessionsScreen=()=> <V2ModuleScreen module="sessions"/>;
function Status({heading,children}:{heading:string;children:ReactNode}){return <section className="premium-empty m-4 sm:m-6"><AlertCircle className="text-muted-foreground"/><h1 className="mt-2 text-xl font-semibold text-foreground">{heading}</h1><div className="mt-2 flex justify-center gap-3 text-sm text-muted-foreground">{children}</div></section>}
