import { useState,type FormEvent,type ReactNode } from 'react';
import { AlertCircle,Clock,Database,Plus,RefreshCw,StopCircle } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { useWork } from '../work/useWork';
import type { WorkSession } from './types';
import { useV2Module,type V2Module } from './useV2Module';

const title=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const display=(record:Record<string,unknown>)=>String(record.name??record.title??record.displayName??record.kind??record.id);

export function V2ModuleScreen({module}:{module:V2Module}){
  const state=useV2Module(module);const work=useWork();const [form,setForm]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!state.scope||!state.user)return;setSaving(true);setMessage('');const data=new FormData(e.currentTarget);try{await state.execute<unknown>(r=>{switch(module){case'milestones':return r.createMilestone(state.scope!,state.user!.id,{projectId:String(data.get('projectId')),name:String(data.get('name')),dueDate:String(data.get('dueDate')||''),estimatedMinutes:Number(data.get('effort'))||undefined});case'subtasks':return r.createSubtask(state.scope!,state.user!.id,{taskId:String(data.get('taskId')),title:String(data.get('name')),estimatedMinutes:Number(data.get('effort'))||undefined});case'departments':return r.createDepartment(state.scope!,String(data.get('name')));case'skills':return r.createSkill(state.scope!,{name:String(data.get('name')),description:String(data.get('description')||'')});default:throw new Error('Creation is not available from this view.');}});setForm(false);}catch{setMessage('The record was not saved. Reload and check your permission or the latest revision.');}finally{setSaving(false);}};
  if(state.loading)return <Status heading={`Loading ${title(module)}…`}>Authoritative organization data is loading.</Status>;
  if(state.error)return <Status heading={`${title(module)} unavailable`}><span>{state.error.message}</span><Button onClick={()=>void state.reload()}><RefreshCw/>Retry</Button></Status>;
  const canCreate=state.isAdmin&&['milestones','subtasks','departments','skills'].includes(module);
  return <main className="premium-page"><header className="flex flex-wrap items-end justify-between gap-3 border-b pb-5"><div><p className="premium-eyebrow">Work OS · {module}</p><h1 className="premium-title mt-1">{title(module)}</h1><p className="mt-1 text-sm text-muted-foreground">Validated, organization-scoped records. Browser state is not authorization.</p></div>{canCreate&&<Button className="rounded-xl" onClick={()=>setForm(v=>!v)}><Plus/>New {title(module).replace(/s$/,'')}</Button>}</header>
    {form&&<form aria-label={`Create ${module}`} onSubmit={submit} className="premium-surface grid max-w-xl gap-3 p-5"><Input name="name" required placeholder={module==='subtasks'?'Subtask title':`${title(module)} name`}/>{module==='skills'&&<Input name="description" placeholder="Description"/>}{module==='milestones'&&<><select name="projectId" required className="h-10 rounded-lg border bg-background px-3"><option value="">Project</option>{work.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Input name="dueDate" type="date"/></>}{module==='subtasks'&&<select name="taskId" required className="h-10 rounded-lg border bg-background px-3"><option value="">Task</option>{work.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select>}{['milestones','subtasks'].includes(module)&&<Input name="effort" type="number" min="0" placeholder="Estimated minutes"/>}<Button disabled={saving}>{saving?'Saving…':'Save'}</Button>{message&&<p role="alert" className="text-sm text-destructive">{message}</p>}</form>}
    {!state.records.length?<Status heading={`No ${title(module).toLowerCase()} yet`}>Nothing authorized is available in this organization.</Status>:<div className="premium-surface divide-y overflow-hidden">{state.records.map(raw=>{const record=raw as Record<string,unknown>;return <article key={String(record.id)} className="flex flex-wrap items-center justify-between gap-3 p-4 transition-colors hover:bg-muted/35"><div><h2 className="font-medium">{display(record)}</h2><p className="text-xs text-muted-foreground">{String(record.status??record.role??record.startedAt??'Active')}</p></div><p className="premium-status">{record.progress!==undefined?`${record.progress}%`:record.availableMinutes!==undefined?`${record.availableMinutes} min available`:'Active'}</p>{module==='sessions'&&!record.endedAt&&record.membershipId===state.scope?.membershipId&&<Button variant="outline" onClick={()=>void state.execute(r=>r.stopWorkSession(record as unknown as WorkSession))}><StopCircle/>Stop</Button>}</article>;})}</div>}
  </main>;
}

export function WorkSessionScreen(){const state=useV2Module('sessions');const active=(state.records as WorkSession[]).find(s=>!s.endedAt&&s.membershipId===state.scope?.membershipId);return <main className="p-6 space-y-5"><h1 className="text-2xl font-semibold">Work Session</h1><p className="text-muted-foreground">Capture time without screenshots, activity monitoring, or employee scoring.</p>{state.loading?<p>Loading active session…</p>:active?<div className="rounded-xl border bg-card p-5"><Clock/><h2 className="font-medium mt-2">Started {new Date(active.startedAt).toLocaleString()}</h2><Button className="mt-4" onClick={()=>void state.execute(r=>r.stopWorkSession(active))}><StopCircle/>Stop session</Button></div>:<Button onClick={()=>void state.execute(r=>r.startWorkSession(state.scope!,{}))}><Clock/>Start session</Button>}</main>}

export function MyWorkScreen(){const work=useWork();if(work.loading)return <Status heading="Loading My Work…">Loading authorized assignments.</Status>;if(work.error)return <Status heading="My Work unavailable">{work.error.message}</Status>;return <main className="premium-page"><header className="border-b pb-5"><p className="premium-eyebrow">Personal command center</p><h1 className="premium-title mt-1">My Work</h1><p className="mt-1 text-sm text-muted-foreground">Prioritized execution across your authorized projects.</p></header><div className="premium-tabs" aria-label="Work filters"><Button size="sm">Today</Button><Button size="sm" variant="ghost">Upcoming</Button><Button size="sm" variant="ghost">Blocked</Button><Button size="sm" variant="ghost">High impact</Button></div><div className="premium-surface divide-y overflow-hidden">{work.tasks.map(task=><article className="grid gap-3 p-4 transition-colors hover:bg-muted/30 sm:grid-cols-[1fr_auto] sm:items-center" key={task.id}><div><h2 className="font-medium">{task.title}</h2><p className="text-sm text-muted-foreground">{task.projectName}</p></div><div className="flex items-center gap-3"><span className="premium-status capitalize">{title(task.status)}</span><div className="w-24"><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${task.progress}%`}}/></div><p className="mt-1 text-right text-[11px] text-muted-foreground">{task.progress}%</p></div></div></article>)}</div>{!work.tasks.length&&<Status heading="No assigned work">Your authorized working set is empty.</Status>}</main>}
export const MilestonesScreen=()=> <V2ModuleScreen module="milestones"/>;export const AssignmentsScreen=()=> <V2ModuleScreen module="assignments"/>;export const WorkReportsScreen=()=> <V2ModuleScreen module="dependencies"/>;
export const PeopleScreen=()=> <V2ModuleScreen module="people"/>;export const DepartmentsScreen=()=> <V2ModuleScreen module="departments"/>;export const TimeEntriesScreen=()=> <V2ModuleScreen module="time"/>;export const SessionsScreen=()=> <V2ModuleScreen module="sessions"/>;
function Status({heading,children}:{heading:string;children:ReactNode}){return <section className="premium-empty m-4 sm:m-6"><AlertCircle className="text-muted-foreground"/><h1 className="mt-2 text-xl font-semibold text-foreground">{heading}</h1><div className="mt-2 flex justify-center gap-3 text-sm text-muted-foreground">{children}</div></section>}
