import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent, type ReactNode } from 'react';
import { Archive, CheckSquare, FolderKanban, Plus, RefreshCw } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { useWork } from './useWork';
import { commitTaskProgress } from './taskProgress';
import type { WorkTask, WorkTaskStatus } from './types';

const TASK_STATUSES: WorkTaskStatus[]=['todo','in_progress','blocked','completed'];
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export function WorkProductionScreen({view}:{view:'projects'|'tasks'}) {
  const work=useWork(); const [showCreate,setShowCreate]=useState(false); const [saving,setSaving]=useState(false); const [mutationError,setMutationError]=useState('');
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setMutationError('');const form=new FormData(event.currentTarget);try{if(view==='projects')await work.createProject({name:String(form.get('name')),description:String(form.get('description')||'')});else await work.createTask({title:String(form.get('title')),description:String(form.get('description')||''),projectId:String(form.get('projectId')),assigneeMembershipId:String(form.get('assignee'))});setShowCreate(false);}catch{setMutationError('The record was not saved. Check the fields and retry.');}finally{setSaving(false);}};
  if(work.loading)return <State title="Loading Work…" detail="Loading authoritative organization records."/>;
  if(work.error)return <State title="Work unavailable" detail={work.error.message}><Button onClick={()=>void work.reload()}><RefreshCw/>Retry</Button></State>;
  const rows=view==='projects'?work.projects:work.tasks;
  return <div className="p-6 space-y-6"><header className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Work / {label(view)}</p><h1 className="text-2xl font-semibold">{label(view)}</h1><p className="text-sm text-muted-foreground mt-1">Persisted, organization-scoped {view}.</p></div>{work.isAdmin&&<Button onClick={()=>setShowCreate(v=>!v)}><Plus/>{view==='projects'?'New project':'New task'}</Button>}</header>
  {showCreate&&<form onSubmit={submit} className="bg-card border rounded-xl p-4 grid gap-3 max-w-2xl" aria-label={`Create ${view==='projects'?'project':'task'}`}><h2 className="font-medium">Create {view==='projects'?'project':'task'}</h2><Input name={view==='projects'?'name':'title'} required maxLength={view==='projects'?160:240} placeholder={view==='projects'?'Project name':'Task title'}/><Input name="description" maxLength={4000} placeholder="Description (optional)"/>{view==='tasks'&&<><select name="projectId" required className="h-9 rounded-md border bg-background px-3"><option value="">Select project</option>{work.projects.filter(p=>p.status!=='archived').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="assignee" required className="h-9 rounded-md border bg-background px-3"><option value="">Select assignee</option>{work.assignees.map(a=><option key={a.membershipId} value={a.membershipId}>{a.label}</option>)}</select></>} {mutationError&&<p role="alert" className="text-sm text-destructive">{mutationError}</p>}<div className="flex gap-2"><Button disabled={saving}>{saving?'Saving…':'Save'}</Button><Button type="button" variant="outline" onClick={()=>setShowCreate(false)}>Cancel</Button></div></form>}
  {rows.length===0?<State title={`No ${view} yet`} detail={work.isAdmin?`Create the first ${view==='projects'?'project':'task'} for this organization.`:`No assigned ${view} are available.`}/>:view==='projects'?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{work.projects.map(p=><article key={p.id} className="bg-card border rounded-xl p-5"><div className="flex justify-between gap-2"><FolderKanban className="text-primary"/><span className="text-xs rounded-full bg-muted px-2 py-1">{label(p.status)}</span></div><h2 className="font-semibold mt-4">{p.name}</h2><p className="text-sm text-muted-foreground mt-1 min-h-10">{p.description||'No description'}</p>{work.isAdmin&&p.status!=='archived'&&<Button className="mt-4" size="sm" variant="outline" onClick={()=>void work.updateProject(p,{status:'archived'})}><Archive/>Archive</Button>}</article>)}</div>:<div className="bg-card border rounded-xl divide-y">{work.tasks.map(t=><TaskRow key={t.id} task={t} isAdmin={work.isAdmin} updateTask={work.updateTask} reload={work.reload}/>)}</div>}</div>;
}

function TaskRow({task,isAdmin,updateTask,reload}:{task:WorkTask;isAdmin:boolean;updateTask:ReturnType<typeof useWork>['updateTask'];reload:ReturnType<typeof useWork>['reload']}) {
  const [draft,setDraft]=useState(String(task.progress)); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const mutationInFlight=useRef(false);
  useEffect(()=>setDraft(String(task.progress)),[task.progress,task.updatedAt]);
  const mutate=async(patch:Parameters<typeof updateTask>[1])=>{if(mutationInFlight.current)return;mutationInFlight.current=true;setSaving(true);setError('');try{await updateTask(task,patch);}catch{setError('The task changed or could not be saved. Authoritative data was reloaded.');await reload();}finally{mutationInFlight.current=false;setSaving(false);}};
  const commit=async()=>{if(mutationInFlight.current)return;mutationInFlight.current=true;setSaving(true);setError('');try{const saved=await commitTaskProgress(task,draft,updateTask,reload);setDraft(String(saved.progress));}catch(e){setError(e instanceof Error&&e.message.startsWith('Progress must')?e.message:'The task changed or could not be saved. Authoritative data was reloaded.');setDraft(String(task.progress));}finally{mutationInFlight.current=false;setSaving(false);}};
  const onProgressKeyDown=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur();}};
  return <article className="p-4 flex flex-col md:flex-row md:items-center gap-3"><CheckSquare className="text-primary"/><div className="flex-1"><h2 className="font-medium">{task.title}</h2><p className="text-xs text-muted-foreground">{task.projectName} · {task.progress}%</p>{error&&<p role="alert" className="text-xs text-destructive mt-1">{error}</p>}</div><select aria-label={`Status for ${task.title}`} value={task.status} disabled={saving||task.status==='archived'} onChange={e=>void mutate({status:e.target.value as WorkTaskStatus})} className="h-9 rounded-md border bg-background px-3">{TASK_STATUSES.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><Input className="w-24" aria-label={`Progress for ${task.title}`} type="number" min="0" max="100" step="1" value={draft} disabled={saving||task.status==='archived'} onChange={e=>setDraft(e.target.value)} onBlur={()=>void commit()} onKeyDown={onProgressKeyDown}/>{isAdmin&&task.status!=='archived'&&<Button size="sm" variant="outline" disabled={saving} onClick={()=>void mutate({status:'archived'})}><Archive/>Archive</Button>}</article>;
}
function State({title,detail,children}:{title:string;detail:string;children?:ReactNode}){return <div className="m-6 rounded-xl border bg-card p-10 text-center"><h1 className="text-xl font-semibold">{title}</h1><p className="text-sm text-muted-foreground mt-2 mb-4">{detail}</p>{children}</div>}
