-- V2 Pass 4: forward-only trusted functional closure.
alter table public.ai_drafts add column revision bigint not null default 1;
alter table public.work_assignments add column revision bigint not null default 1, add column archived_at timestamptz;
alter table public.task_dependencies add column revision bigint not null default 1, add column archived_at timestamptz;
alter table public.messages add column revision bigint not null default 1;
alter table public.conversation_members add column archived_at timestamptz;

create table public.autopilot_approvals(
 id uuid primary key default extensions.gen_random_uuid(), idempotency_key uuid not null unique,
 tenant_id uuid not null, organization_id uuid not null, draft_id uuid not null unique references public.ai_drafts(id),
 project_id uuid not null, approved_by uuid not null references auth.users(id), audit_event_id uuid not null references public.audit_events(id), created_at timestamptz not null default now(),
 foreign key(project_id,organization_id,tenant_id) references public.projects(id,organization_id,tenant_id));
alter table public.autopilot_approvals enable row level security; alter table public.autopilot_approvals force row level security;
create policy autopilot_approvals_admin_read on public.autopilot_approvals for select to authenticated using(private.is_work_org_admin(organization_id));
revoke all on public.autopilot_approvals from public,anon,authenticated; grant select on public.autopilot_approvals to authenticated;

create or replace function private.require_work_admin(p_organization_id uuid) returns public.memberships language plpgsql stable security definer set search_path=pg_catalog,public as $$
declare result public.memberships; begin select * into result from public.memberships where user_id=auth.uid() and organization_id=p_organization_id and role='org_admin' and status='active' and deleted_at is null;
 if result.id is null then raise exception 'organization administrator required' using errcode='42501'; end if; return result; end$$;

create or replace function public.mutate_assignment(p_id uuid,p_organization_id uuid,p_expected_revision bigint,p_task_id uuid,p_subtask_id uuid,p_membership_id uuid,p_allocated_minutes int,p_archive boolean default false) returns public.work_assignments language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare admin public.memberships; result public.work_assignments; begin admin:=private.require_work_admin(p_organization_id);
 if not exists(select 1 from public.memberships where id=p_membership_id and tenant_id=admin.tenant_id and organization_id=p_organization_id and status='active' and deleted_at is null and role<>'platform_admin') then raise exception 'active organization assignee required' using errcode='42501'; end if;
 if (p_task_id is not null)::int+(p_subtask_id is not null)::int<>1 then raise exception 'exactly one assignment target required' using errcode='22023'; end if;
 if p_id is null then insert into public.work_assignments(tenant_id,organization_id,task_id,subtask_id,membership_id,status,allocated_minutes,assigned_by) values(admin.tenant_id,p_organization_id,p_task_id,p_subtask_id,p_membership_id,'accepted',p_allocated_minutes,auth.uid()) returning * into result;
 else update public.work_assignments set membership_id=p_membership_id,allocated_minutes=p_allocated_minutes,archived_at=case when p_archive then now() else null end,revision=revision+1,updated_at=now() where id=p_id and organization_id=p_organization_id and revision=p_expected_revision returning * into result; end if;
 if result.id is null then raise exception 'assignment conflict' using errcode='40001'; end if; return result; end$$;

create or replace function public.mutate_dependency(p_id uuid,p_organization_id uuid,p_expected_revision bigint,p_predecessor uuid,p_successor uuid,p_remove boolean default false) returns public.task_dependencies language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare admin public.memberships; result public.task_dependencies; begin admin:=private.require_work_admin(p_organization_id);
 if not exists(select 1 from public.tasks where id=p_predecessor and organization_id=p_organization_id and tenant_id=admin.tenant_id) or not exists(select 1 from public.tasks where id=p_successor and organization_id=p_organization_id and tenant_id=admin.tenant_id) then raise exception 'scoped task references required' using errcode='23503'; end if;
 if p_id is null then insert into public.task_dependencies(tenant_id,organization_id,predecessor_task_id,successor_task_id,created_by) values(admin.tenant_id,p_organization_id,p_predecessor,p_successor,auth.uid()) returning * into result;
 else update public.task_dependencies set archived_at=case when p_remove then now() else null end,revision=revision+1 where id=p_id and organization_id=p_organization_id and revision=p_expected_revision returning * into result; end if;
 if result.id is null then raise exception 'dependency conflict' using errcode='40001'; end if; return result; end$$;

create or replace function public.mark_all_notifications_read(p_organization_id uuid) returns integer language plpgsql security definer set search_path=pg_catalog,public,private as $$declare member uuid; affected int; begin member:=private.current_work_membership(p_organization_id); if member is null then raise exception 'active Work membership required' using errcode='42501'; end if; update public.notifications set read_at=now() where organization_id=p_organization_id and recipient_membership_id=member and read_at is null; get diagnostics affected=row_count; return affected; end$$;

create or replace function public.process_deadline_notifications(p_as_of date default current_date) returns integer language plpgsql security definer set search_path=pg_catalog,public as $$declare affected int; begin
 if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501'; end if;
 insert into public.notifications(tenant_id,organization_id,recipient_membership_id,kind,title,body,entity_type,entity_id)
 select t.tenant_id,t.organization_id,t.assignee_membership_id,'deadline','Task deadline',case when t.due_date<p_as_of then 'Overdue' else 'Due soon' end,'task',t.id from public.tasks t where t.archived_at is null and t.status<>'completed' and t.assignee_membership_id is not null and t.due_date between p_as_of-30 and p_as_of+3 and not exists(select 1 from public.notifications n where n.recipient_membership_id=t.assignee_membership_id and n.kind='deadline' and n.entity_id=t.id and n.created_at::date=p_as_of);
 get diagnostics affected=row_count; return affected; end$$;

create or replace function public.dispatch_offline_mutation(p_mutation_id uuid) returns public.offline_mutations language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare q public.offline_mutations; member uuid; task public.tasks; begin select * into q from public.offline_mutations where id=p_mutation_id for update;
 if q.id is null then raise exception 'mutation not found' using errcode='P0002'; end if; if q.status='applied' then return q; end if;
 member:=private.current_work_membership(q.organization_id); if member is null or member<>q.membership_id then update public.offline_mutations set status='rejected',failure_code='authorization_revoked' where id=q.id returning * into q; return q; end if;
 if q.entity_type='task' and q.operation='update_lifecycle' then select * into task from public.tasks where id=q.entity_id and organization_id=q.organization_id; if task.id is null then raise exception 'task unavailable' using errcode='42501'; end if; if task.revision<>q.base_revision then update public.offline_mutations set status='conflict',conflict=jsonb_build_object('server_revision',task.revision),failure_code='revision_changed' where id=q.id returning * into q; return q; end if;
  update public.tasks set status=coalesce((q.payload->>'status')::public.work_task_status,status),progress=case when q.payload->>'status'='completed' then 100 when q.payload->>'status'='todo' or status='completed' then 0 else coalesce((q.payload->>'progress')::smallint,progress) end where id=task.id;
 elsif q.entity_type='message' and q.operation='send' then perform public.post_message((q.payload->>'conversation_id')::uuid,q.payload->>'body','{}'::uuid[]);
 else update public.offline_mutations set status='rejected',failure_code='unsupported_operation' where id=q.id returning * into q; return q; end if;
 update public.offline_mutations set status='applied',server_applied_at=now(),failure_code=null where id=q.id returning * into q; return q;
exception when others then update public.offline_mutations set status='rejected',failure_code='server_validation' where id=p_mutation_id returning * into q; return q; end$$;

create or replace function public.approve_autopilot_draft(p_draft_id uuid,p_expected_revision bigint,p_idempotency_key uuid) returns public.autopilot_approvals language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare d public.ai_drafts; request public.ai_requests; admin public.memberships; project public.projects; approval public.autopilot_approvals; audit_id uuid; item jsonb; child jsonb; dep jsonb; member_id uuid; milestone_id uuid; task_id uuid; milestone_map jsonb:='{}'; task_map jsonb:='{}'; begin
 select * into approval from public.autopilot_approvals where idempotency_key=p_idempotency_key; if approval.id is not null then return approval; end if;
 select * into d from public.ai_drafts where id=p_draft_id for update; if d.id is null or d.status<>'approved' or d.revision<>p_expected_revision then raise exception 'stale or unapproved draft' using errcode='40001'; end if;
 select * into request from public.ai_requests where id=d.request_id; admin:=private.require_work_admin(request.organization_id); if d.draft_type<>'project_autopilot' then raise exception 'invalid draft type' using errcode='22023'; end if;
 insert into public.projects(tenant_id,organization_id,name,description,priority,start_date,due_date,estimated_minutes,owner_membership_id,created_by) values(request.tenant_id,request.organization_id,d.payload#>>'{project,name}',d.payload#>>'{project,description}',coalesce((d.payload#>>'{project,priority}')::public.work_priority,'normal'),nullif(d.payload#>>'{project,startDate}','')::date,nullif(d.payload#>>'{project,dueDate}','')::date,nullif(d.payload#>>'{project,estimatedMinutes}','')::int,admin.id,auth.uid()) returning * into project;
 for item in select * from jsonb_array_elements(coalesce(d.payload->'milestones','[]')) loop milestone_id:=extensions.gen_random_uuid(); milestone_map:=milestone_map||jsonb_build_object(item->>'clientId',milestone_id); insert into public.milestones(id,tenant_id,organization_id,project_id,name,description,start_date,due_date,estimated_minutes,created_by) values(milestone_id,request.tenant_id,request.organization_id,project.id,item->>'name',item->>'description',nullif(item->>'startDate','')::date,nullif(item->>'dueDate','')::date,nullif(item->>'estimatedMinutes','')::int,auth.uid()); end loop;
 for item in select * from jsonb_array_elements(coalesce(d.payload->'tasks','[]')) loop
  milestone_id:=(milestone_map->>(item->>'milestoneClientId'))::uuid; if milestone_id is null then raise exception 'invalid milestone reference' using errcode='23503'; end if; task_id:=extensions.gen_random_uuid(); task_map:=task_map||jsonb_build_object(item->>'clientId',task_id);
  member_id:=nullif(item#>>'{assigneeMembershipIds,0}','')::uuid; if member_id is not null and not exists(select 1 from public.memberships where id=member_id and tenant_id=request.tenant_id and organization_id=request.organization_id and status='active' and deleted_at is null and role<>'platform_admin') then raise exception 'inactive or cross-organization assignee' using errcode='42501'; end if;
  insert into public.tasks(id,tenant_id,organization_id,project_id,milestone_id,title,description,start_date,due_date,estimated_minutes,assignee_membership_id,created_by) values(task_id,request.tenant_id,request.organization_id,project.id,milestone_id,item->>'title',item->>'description',nullif(item->>'startDate','')::date,nullif(item->>'dueDate','')::date,nullif(item->>'estimatedMinutes','')::int,coalesce(member_id,admin.id),auth.uid());
  for member_id in select jsonb_array_elements_text(coalesce(item->'assigneeMembershipIds','[]'))::uuid loop if not exists(select 1 from public.memberships where id=member_id and tenant_id=request.tenant_id and organization_id=request.organization_id and status='active' and deleted_at is null and role<>'platform_admin') then raise exception 'inactive or cross-organization assignee' using errcode='42501'; end if; insert into public.work_assignments(tenant_id,organization_id,task_id,membership_id,status,allocated_minutes,assigned_by) values(request.tenant_id,request.organization_id,task_id,member_id,'accepted',nullif(item->>'estimatedMinutes','')::int,auth.uid()); end loop;
  for child in select * from jsonb_array_elements(coalesce(item->'subtasks','[]')) loop insert into public.subtasks(tenant_id,organization_id,task_id,title,description,estimated_minutes,created_by) values(request.tenant_id,request.organization_id,task_id,child->>'title',child->>'description',nullif(child->>'estimatedMinutes','')::int,auth.uid()); end loop;
 end loop;
 for dep in select * from jsonb_array_elements(coalesce(d.payload->'dependencies','[]')) loop if task_map->>(dep->>'predecessorId') is null or task_map->>(dep->>'successorId') is null then raise exception 'invalid dependency reference' using errcode='23503'; end if; insert into public.task_dependencies(tenant_id,organization_id,predecessor_task_id,successor_task_id,created_by) values(request.tenant_id,request.organization_id,(task_map->>(dep->>'predecessorId'))::uuid,(task_map->>(dep->>'successorId'))::uuid,auth.uid()); end loop;
 insert into public.audit_events(actor_user_id,tenant_id,organization_id,actor_role,action,target_type,target_id,source,metadata) values(auth.uid(),request.tenant_id,request.organization_id,'org_admin','ai.autopilot.materialized','project',project.id,'database_trigger',jsonb_build_object('draft_id',d.id)) returning id into audit_id;
 update public.ai_drafts set status='applied',revision=revision+1 where id=d.id; insert into public.autopilot_approvals(idempotency_key,tenant_id,organization_id,draft_id,project_id,approved_by,audit_event_id) values(p_idempotency_key,request.tenant_id,request.organization_id,d.id,project.id,auth.uid(),audit_id) returning * into approval; return approval; end$$;

revoke all on function public.mutate_assignment(uuid,uuid,bigint,uuid,uuid,uuid,int,boolean),public.mutate_dependency(uuid,uuid,bigint,uuid,uuid,boolean),public.mark_all_notifications_read(uuid),public.dispatch_offline_mutation(uuid),public.approve_autopilot_draft(uuid,bigint,uuid) from public,anon;
grant execute on function public.mutate_assignment(uuid,uuid,bigint,uuid,uuid,uuid,int,boolean),public.mutate_dependency(uuid,uuid,bigint,uuid,uuid,boolean),public.mark_all_notifications_read(uuid),public.dispatch_offline_mutation(uuid),public.approve_autopilot_draft(uuid,bigint,uuid) to authenticated;
revoke all on function public.process_deadline_notifications(date) from public,anon,authenticated; grant execute on function public.process_deadline_notifications(date) to service_role;
